### PR TITLE
Updated Atlassian JIRA Software master branch to latest version 7.1.5

### PR DESCRIPTION
**Pull request by nogara**
I received an alert today with this upgrade. It seems nothing important changed, but just to keep it updated.

### CODE REVIEW

**Comment by cptactionhank** [comment]
Hi Luiz, i'm sorry that I can't accept this pull request unconditionally and merge it straight away since the CircleCI acceptance tests are failing. 

I'll look into this as soon as possible.

Kind regards,

Martin Jensen

**Comment by nogara** [comment]
Of course! From what I've seen, the fail is related to a timeout in some process, but since I was not sure how to force the test to run again I just let it be.

**Comment by cptactionhank** [comment]
I think it is caused by a change in the web setup wizard one have to go through, which is what I test for goes fine with embedded, Postgres, and MySQL databases, and a proxy test as well.

Unfortunately I won't have time to look into this before the weekend though.

Fun fact: I have an automated setup that checks for new releases every night (around midnight CEST) and initiates a new build when found. However for the branches and image tags to be created the acceptance tests has to pass first.

Kind regards,

Martin Jensen

**Comment by cptactionhank** [comment]
Closing this PR due to the following Atlassian notice:

> This release has been cancelled due to a bug that affects MySQL and Microsoft SQL Server databases. We are working on resolving this issue for our next release. For more information on the bug you can view  JRA-60729 - Upgrading JIRA to 7.1.5 breaks due to incorrect syntax in ALTER SQL AWAITING SOAK .
> This bug only affects customers using Microsoft SQL Server and MySQL databases. If you are not using either of these databases, you will not be affected by this bug. Should you need further assistance please do reach out to us at https://support.atlassian.com.

**Pull request closed without merging**
