### PR TITLE
Allow Java HEAP size control via env variables

### PR DESCRIPTION
**Pull request by seb-steuer**
Hi,

I thought it would be beneficial to have a HEAP size control via ENV variables.

Kind regards
Sebastian

### CODE REVIEW

**Comment by jimsmith** [comment]
@cptactionhank hey great work on making this a dockerfile.
I like this pull request as this solves alot of challenges I am facing could this be progressed ? I see there is a conflict but I don't think there was previously though.

+1

**Comment by cptactionhank** [comment]
Set the environment variable CATALINA_OPTS with eg. `-Xms1024m -Xmx2048m` instead

```
docker create --restart=no --name "jira-container" \
    --publish "8080:8080" \
    --env "CATALINA_OPTS=-Xms1024m -Xmx2048m -Datlassian.plugins.enable.wait=300" \
    cptactionhank/atlassian-jira:latest
```

**Comment by jimsmith** [comment]
Thanks.   There are hardcoded options in the Dockerfile these should be variables.

**Comment by cptactionhank** [comment]
Closing this as it is not needed, set the java options through `CATALINA_OPTS` environment variable.

**Comment by jimsmith** [comment]
that is a shame as the url is hardcoded to a specific version :(

thanks anyways perhaps forking off elsewhere is the only viable option pity though. ok

**Comment by cptactionhank** [comment]
Creating a container on this image will _not_ download and install the version in the defined environment variable. If you are seeking a specific version use another tag than latest.

**Comment by jimsmith** [comment]
👍👌

**Pull request closed without merging**
